FROM fogrosbaseimage_coverity

COPY coverity.yaml /main_ws/src/
# RUN chmod /main_ws/src/auth-key.txt

COPY . /main_ws/src/
RUN git config --global --add safe.directory /main_ws/src

ARG COVERITY_PASSPHRASE
ENV COVERITY_PASSPHRASE=${COVERITY_PASSPHRASE}
ENV COVERITY_CLI_CONNECT_USERNAME=cov_scan

ENTRYPOINT [ "entrypoint-coverity.sh" ]
