name: build

on:
  pull_request:
  push:
    branches:
      - ci

env:
  ROS_DISTRO: foxy
  ROS_VERSION: ros2
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    shell: bash
      
jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Using Docker
      run: |
        export DOCKER_IMAGE=krishneel/ros2-foxy:latest
        export CI_SOURCE_PATH=$(pwd)
        export REPO_NAME=${{ github.event.repository.name }}
        export HOME=$GITHUB_WORKSPACE
        docker run -v $HOME:$HOME -e CI_SOURCE_PATH -e $REPO_NAME -e HOME $DOCKER_IMAGE bash -c 'cd $CI_SOURCE_PATH; source .github/travis.sh'
