name: tii-octomap-server2

on:
  repository_dispatch:
  push:

jobs:
  coverity:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build coverity scan image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: coverity-scan-image:latest
          file: Dockerfile.coverity
      - name: run coverity static analysis
        env:
          COV_USER: cov_scan
          COVERITY_PASSPHRASE: ${{ secrets.COVERITY_PASSPHRASE }}
        uses: addnab/docker-run-action@v3
        with:
          image: coverity-scan-image:latest
          options: -v /mnt/jenkins/coverity/cov-analysis-linux64-2022.9.1:/cov -e COVERITY_PASSPHRASE=${{ secrets.COVERITY_PASSPHRASE }} -e COV_USER=cov_scan
          run: |
            /cov/bin/cov-manage-im --mode auth-key --create --output-file auth_key.txt --url https://coverity.ssrc.fi:443 --user cov_scan --set description:"ci github action" --set expiration:"after_1_days"
            auth_key_id=$(grep -oh id\":[[:digit:]]\\+ auth_key.txt |grep -oh [[:digit:]]\\+)
            /cov/bin/coverity scan --exclude-language java
            /cov/bin/coverity list
            /cov/bin/cov-manage-im --mode auth-key --revoke $auth_key_id
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz
